repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort
      name: isort (python)

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==22.1.11]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
    - id: mypy
      additional_dependencies: [types-requests, types-python-dateutil]
      exclude: ^tests/
      args: [--ignore-missing-imports, --disallow-untyped-defs, --strict]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    - id: python-check-blanket-noqa
    - id: python-check-mock-methods
    - id: python-no-log-warn
    - id: python-use-type-annotations

-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    - id: blacken-docs
      additional_dependencies: [black==22.3.0]

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    - id: mdformat
      additional_dependencies: [mdformat-gfm, mdformat-black, mdformat-toc]
      args: [--wrap=88]

ci:
  autofix_commit_msg: "style: [pre-commit.ci] auto fixes from pre-commit.com hooks"
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: [mypy]  # mypy is too slow for CI
