# [START runtime]
runtime: python39

# [START env]
env: flex
# [END env]

# [START entrypoint]
entrypoint: gunicorn -b :$PORT main:app --timeout 180 --workers 4 --worker-class gthread --threads 2
# [END entrypoint]

# [START runtime_config]
runtime_config:
  python_version: 3.9
# [END runtime_config]

# [START service]
service: default
# [END service]

# [START resources]
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
# [END resources]

# [START env_variables]
env_variables:
  # Application settings
  FLASK_APP: "main.py"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  
  # Database configuration
  DB_USER: "root"
  DB_PASS: "TuContrase침aSegura123!"  # Reemplaza con tu contrase침a real
  DB_NAME: "florezcook_db"
  DB_SOCKET_DIR: "/cloudsql"
  CLOUD_SQL_CONNECTION_NAME: "florezcook:us-central1:florezcook-db"
  
  # Google Cloud settings
  GOOGLE_CLOUD_PROJECT: "florezcook"
  
  # Security
  SECRET_KEY: "florezcook-secret-key-prod-$(openssl rand -hex 32)"  # Genera una clave secreta aleatoria
# [END env_variables]

# [START beta_settings]
beta_settings:
  cloud_sql_instances: "florezcook:us-central1:florezcook-db"
# [END beta_settings]

# [START automatic_scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.6
  cool_down_period_sec: 180
# [END automatic_scaling]

# [START health_checks]
# Health check configuration
liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

# Readiness check
readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
# [END health_checks]

# [START handlers]
handlers:
# Serve static files from the 'static' directory
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

# Serve the main application
- url: /.*
  secure: always
  script: auto
  redirect_http_response_code: 301
# [END handlers]

# [START network_settings]
network:
  instance_tag: "florezcook-app"
  name: "default"
  subnetwork_name: "default"
  session_affinity: false
# [END network_settings]

# [START service_account]
# La cuenta de servicio debe ser una direcci칩n de correo electr칩nico o se puede eliminar para usar la cuenta predeterminada
# service_account: "florezcook@appspot.gserviceaccount.com"
# [END service_account]

# Version is automatically managed by gcloud and should not be specified in app.yaml
