runtime: python
env: flex

# Configuración del entorno de ejecución
runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.11"

# Configuración del servicio
service: default

# Recursos asignados
resources:
  cpu: 1
  memory_gb: 2  # Aumentado a 2GB para mejor rendimiento
  disk_size_gb: 10

# Variables de entorno
env_variables:
  # Configuración de la aplicación
  FLASK_APP: "main.py"
  FLASK_ENV: "production"
  PYTHONUNBUFFERED: "1"
  
  # Configuración de la base de datos
  # Estas variables se sobrescribirán con los secretos de Cloud Secret Manager
  DB_NAME: "florezcook_db"
  DB_USER: "root"
  
  # Configuración de Cloud SQL
  CLOUD_SQL_CONNECTION_NAME: "${CLOUD_SQL_CONNECTION_NAME}"
  DB_SOCKET_DIR: "/cloudsql"
  
  # Google Cloud
  GOOGLE_CLOUD_PROJECT: "florezcook"
  
  # Seguridad
  SECRET_KEY: "${SECRET_KEY}"

# Configuración de Cloud SQL
beta_settings:
  cloud_sql_instances: "florezcook:us-central1:florezcook-db"

# Escalado automático
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  target_cpu_utilization: 0.65
  cool_down_period_sec: 180

# Health checks
liveness_check:
  path: "/healthz"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 300

readiness_check:
  path: "/readiness"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

# Manejadores de URL
handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: /.*
  secure: always
  script: auto
  redirect_http_response_code: 301

# Configuración de red
network:
  instance_tag: "florezcook-app"
  name: "default"
  forwarded_ports:
    - 80:8080
    - 443:8080
  session_affinity: false

# Cuenta de servicio
service_account: "${SERVICE_ACCOUNT_EMAIL}"

# Nota: La versión se maneja automáticamente por gcloud
