# Configuración de Cloud Build para FlorezCook
# Este archivo define los pasos de construcción para implementar la aplicación en Google Cloud Platform

steps:
  # Paso 1: Instalar dependencias de Python
  - name: 'python:3.11'
    id: 'install-dependencies'
    entrypoint: bash
    args:
      - '-c'
      - |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -t lib --upgrade
        # Instalar dependencias para el sistema operativo
        apt-get update && apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            python3-dev \
            libmysqlclient-dev
    waitFor: ['-']
    # Usar caché para acelerar las construcciones
    volumes:
      - name: 'pip-cache'
        path: '/root/.cache/pip'

  # Paso 2: Ejecutar pruebas (opcional)
  # - name: 'python:3.11'
  #   id: 'run-tests'
  #   entrypoint: bash
  #   args: ['-c', 'python -m pytest tests/']
  #   env:
  #     - 'FLASK_APP=main.py'
  #     - 'FLASK_ENV=testing'
  #   waitFor: ['install-dependencies']

  # Paso 3: Desplegar en App Engine Flexible
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-app'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Configurar el proyecto de GCP
        gcloud config set project ${PROJECT_ID}
        
        # Habilitar las APIs necesarias
        gcloud services enable appengineflex.googleapis.com
        gcloud services enable sqladmin.googleapis.com
        
        # Desplegar la aplicación
        gcloud app deploy \
          app.yaml \
          --project=${PROJECT_ID} \
          --version=${SHORT_SHA} \
          --promote \
          --quiet
    # Variables de entorno para la autenticación
    env:
      - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'
    # Tiempo de espera más largo para el despliegue
    timeout: 1200s  # 20 minutos
    waitFor: ['install-dependencies']
    waitFor: ['install-dependencies']
    # Allow the Cloud Build service account to access Cloud SQL
    # Make sure the Cloud Build service account has the 'Cloud SQL Client' role
    # and the 'Cloud SQL Instance User' role on the Cloud SQL instance
    env:
      - 'CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=/workspace/key.json'
    secretEnv: ['DB_PASSWORD']

# Timeout for the build (10 minutes)
timeout: 600s

# [START substitutions]
# These variables can be overridden when triggering the build
substitutions:
  # Database configuration
  _DB_USER: 'root'  # Default value, can be overridden
  _DB_PASS: ''      # Should be provided when triggering the build
  _DB_NAME: 'florezcook_db'
  _CLOUD_SQL_CONNECTION_NAME: '${PROJECT_ID}:us-central1:florezcook-db'  # Adjust region as needed
# [END substitutions]

# [START available_secrets]
# These secrets will be available to build steps
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/DB_PASSWORD/versions/latest
      env: 'DB_PASSWORD'
# [END available_secrets]

# [START artifacts]
# Store build artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}_cloudbuild/artifacts/'
    paths: ['app.yaml', 'main.py', 'requirements.txt']
# [END artifacts]

# [START options]
options:
  logging: CLOUD_LOGGING_ONLY
  # Use a more powerful machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Increase timeout for the build
  timeout: 1200s  # 20 minutes
# [END options]

# [START images]
# Push images to Container Registry
images:
  - 'gcr.io/${PROJECT_ID}/florezcook:${SHORT_SHA}'
  - 'gcr.io/${PROJECT_ID}/florezcook:latest'
# [END images]

# [START tags]
# Add tags to the build
tags:
  - 'florezcook'
  - 'app-engine'
  - 'python'
  - 'flask'
# [END tags]

# [START service_account]
# Use a custom service account with necessary permissions
serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/cloud-build@${PROJECT_ID}.iam.gserviceaccount.com'
# [END service_account]

# [START secrets]
# Use secrets from Secret Manager
secrets:
  - kmsKeyName: projects/${PROJECT_ID}/locations/global/keyRings/my-key-ring/cryptoKeys/my-key
    secretEnv:
      _DB_PASSWORD: 'projects/123456789012/secrets/DB_PASSWORD/versions/latest'
# [END secrets]

# [START include]
# Include other configuration files
include:
  - path: 'cloudbuild-tests.yaml'
    timeout: 600s
# [END include]

# [END cloudbuild_yaml]

# Variables de tiempo de espera
timeout: 1200s  # 20 minutos

# Opcional: Artifacts a guardar después del build
# artifacts:
#   objects:
#     location: 'gs://[YOUR_BUCKET_NAME]/'
#     paths: ['app.yaml', 'main.py', 'requirements.txt']

# Opcional: Notificaciones
# options:
#   logging: CLOUD_LOGGING_ONLY

# Opcional: Configuración de máquina
# options:
#   machineType: 'N1_HIGHCPU_8'  # Usar una máquina más potente si es necesario
