# [START docker-compose]
version: '3.8'

services:
  # Base de datos MySQL (simplificado para desarrollo rápido)
  database:
    image: mysql:8.0
    container_name: florezcook-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-florezcook_root_2025_secure}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-florezcook}
      MYSQL_USER: ${MYSQL_USER:-florezcook_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-florezcook_pass_2025_secure}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - florezcook-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
      interval: 15s
      start_period: 30s

  # Solo aplicación Admin para empezar
  app-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: florezcook-admin
    restart: unless-stopped
    ports:
      - "${ADMIN_PORT:-8080}:8080"
    environment:
      - ENV=${ENV:-development}
      - DEBUG=${DEBUG:-true}
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-florezcook_user}:${MYSQL_PASSWORD:-florezcook_pass_2025_secure}@database:3306/${MYSQL_DATABASE:-florezcook}
      - SECRET_KEY=${SECRET_KEY:-docker-florezcook-admin-secret-2025}
      - FLASK_ENV=${FLASK_ENV:-development}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - florezcook-network
    volumes:
      - ${LOGS_PATH:-./logs}:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      timeout: 5s
      retries: 3
      interval: 20s
      start_period: 30s

networks:
  florezcook-network:
    driver: bridge
    name: ${NETWORK_NAME:-florezcook-network}

volumes:
  mysql_data:
    driver: local
    name: ${MYSQL_DATA_VOLUME:-florezcook-mysql-data}
# [END docker-compose]
